# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('scopeCleaned', models.CharField(max_length=20)),
                ('institutionType', models.CharField(max_length=20)),
                ('issueFocus', models.CharField(max_length=20)),
                ('latitidue', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sources', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=15)),
                ('weight', models.IntegerField()),
                ('affiltype', models.CharField(max_length=20)),
                ('regultype', models.CharField(max_length=20)),
            ],
        ),
    ]
