# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClimateAdaptationMitigation', '0003_auto_20171116_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='abbr',
            new_name='abr',
        ),
    ]
