# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClimateAdaptationMitigation', '0004_auto_20171116_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='abr',
            new_name='Abr',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='institutionType',
            new_name='InstitutionType',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='issueFocus',
            new_name='IssueFocus',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='label',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='latitidue',
            new_name='Lat',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='longitude',
            new_name='Lng',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='scopeCleaned',
            new_name='ScopeCleaned',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='sources',
            new_name='source',
        ),
    ]
