# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClimateAdaptationMitigation', '0005_auto_20171116_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='InstitutionType',
            new_name='InstitutionalType',
        ),
    ]
