# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClimateAdaptationMitigation', '0007_auto_20171204_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edges',
            old_name='type',
            new_name='types',
        ),
    ]
